title: Kevin McLaughlin # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
subtitle: Maker
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science Undergrad<br>
  Queen's University Belfast
  <br><br>
  I have a passion for making. Check out some of my projects!
  <a href="https://www.linkedin.com/in/kevin-mclaughlin-/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
