title: Kevin McLaughlin # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
subtitle: Maker
description: > # your text below (remove <br> elements if you don't need line breaks)
  Making things! Hardware and Software Projects.
sidebar: >  
  Computer Science Undergrad<br>
  Queen's University Belfast
  <br><br>
  I have a passion for making. Check out some of my projects!
  <br><br>
  <b><a href="https://kmclaughlin.github.io/#software-projects">Software Projects</a></b>
  <br>
  <b><a href="https://kmclaughlin.github.io/#hardware-projects">Hardware Projects</a></b>
  <br><br>
  <a href="https://www.linkedin.com/in/kevin-mclaughlin-/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-142694314-1
